import type { Metadata } from "next";
import "../globals.css";
import { ReactElement } from "react";
import { Providers } from "../providers";
import { I18nProviderClient } from "@/app/messages/client";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({
  params: { locale },
  children,
}: {
  params: { locale: string };
  children: ReactElement;
}) {
  return (
    <html>
      <body>
        <I18nProviderClient locale={locale}>
          <Providers>{children}</Providers>
        </I18nProviderClient>
      </body>
    </html>
  );
}
